Added frenchify, copied nearly exactly from the php frenchify
brandons209/Script-Generator-Cog pull request #14
Opened 2021-01-06 05:09 UTC by TheScriptPony

frenchify is a lot of lines, hence all the changes. Also modified bify a little bit, so that's the removed stuff

2021-01-07 02:32 UTC, TheScriptPony commented
Wait do I need to update the info.json to include the guy who made the php?

2021-01-07 02:41 UTC, shroomdog27 commented
Crediting the original author would be appreciated, yes. Personally, I'd suggest editing the info.json to include the author's name, and include a comment in the copied code that source where it came from.

In addition, make sure that you have permission to copy code. We're [GPL3](https://github.com/brandons209/Red-bot-Cogs/blob/v3/LICENSE), so make sure the place you are copying from allows us to use it. You can ask if you can't figure it out, just drop a link to where you got it from.

2021-01-07 05:31 UTC, brandons209 requested changes

2021-01-07 05:31 UTC, brandons209 commented on memeify/memeify.py
> +        emoji_match = re.finditer(custom_emoji, french_str)
Big error. `french_str` can be referenced before assignment if cmd is not none. You need an else for this statement to sent french_str (or move this under the if statement.

2021-01-07 05:31 UTC, brandons209 commented on memeify/memeify.py
> +        emoji_match = re.finditer(custom_emoji, french_str)
Happens when you run frenchify with no text.

2021-01-10 01:43 UTC, brandons209 approved these changes
Alright, looks good!

2021-01-10 01:43 UTC, merged